#!/bin/bash
docker run --rm                         `# remove container after use` \
    -i                                  `# interactive mode` \
    -v $(pwd -P):$(pwd -P)              `# share current directory` \
    -w $(pwd -P)                        `# make current directory as latex working directory` \
    harmish/haskell:diagrams hlint "$@" `# run hlint container passing all user args`
