#!/bin/sh

# setting the robot
case "$HOST" in
    "maxc1")
    ROBOT="pr2"
    ROS_DISTRO="hydro"
    ;;
    "maxc2")
    ROBOT="pr2"
    ROS_DISTRO="hydro"
    ;;
    "bobc1")
    ROBOT="pr2"
    ROS_DISTRO="indigo"
    ;;
    "bobc2")
    ROBOT="pr2"
    ROS_DISTRO="indigo"
    ;;
    *)
    ROBOT=""
    ;;
esac

# do addtional stuff on the robots when required
if [[ $ROBOT == "pr2" ]]; then
    # following variables are needed for the pr2 robot
    export LC_ALL="en_US.UTF-8"
    export ROS_ENV_LOADER=/etc/ros/$ROS_DISTRO/env.sh
fi

# setting up anymal
anymal () {
    version=$1
    export ROS_MASTER_URI=http://anymal-$version-lpc:11311
    export ROS_IP=`ifconfig | grep 'inet 192.168' | awk '{print $2}'`
    alias anymal_lpc='ssht $USER@anymal-$version-lpc'
    alias anymal_npc='ssht $USER@anymal-$version-npc'
    alias anymal_apc='ssht $USER@anymal-$version-apc'
    alias anymal_opc='ssht $USER@anymal-$version-opc'
    if ! grep -q "anymal-$version-lpc" /etc/chrony/chrony.conf; then
        sudo sed -i "s/anymal-.*-lpc/anymal-$version-lpc/" /etc/chrony/chrony.conf
        sudo service chrony restart # can take some time if changing robots infrequently leave commented
    fi
    echo "Setup ros environment variables and shortcuts for anymal $version"
}
