#!/bin/sh

# setting the robot
case "$HOST" in
    "maxc1")
    ROBOT="pr2"
    ROS_DISTRO="hydro"
    ;;
    "maxc2")
    ROBOT="pr2"
    ROS_DISTRO="hydro"
    ;;
    "bobc1")
    ROBOT="pr2"
    ROS_DISTRO="indigo"
    ;;
    "bobc2")
    ROBOT="pr2"
    ROS_DISTRO="indigo"
    ;;
    *)
    ROBOT=""
    ;;
esac

# do addtional stuff on the robots when required
if [[ $ROBOT == "pr2" ]]; then
    # following variables are needed for the pr2 robot
    export LC_ALL="en_US.UTF-8"
    export ROS_ENV_LOADER=/etc/ros/$ROS_DISTRO/env.sh
fi
